substitution
basybemoog/cs50 pull request #23
Opened 2024-04-10 19:33 UTC by basybemoog

2024-04-11 19:22 UTC, basybemoog commented
Изменил, все кейсы проходит, не ругайся только за колхоз, но проверку на дупликаты, спасибо литкоду)

2024-04-12 19:47 UTC, fastrapier requested changes
Верни файл .gitignore в исходное состояние

2024-04-12 19:47 UTC, fastrapier commented on .gitignore
Неверно не понял зачем ты вообще решил изменить этот файл

2024-04-13 08:42 UTC, fastrapier requested changes

2024-04-13 08:42 UTC, fastrapier commented on .gitignore
оставь файл go.mod в покое!! Он нужен для проекта

2024-04-13 08:43 UTC, fastrapier commented
@basybemoog https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=23&id=study-kirill_stdu
<img width="1680" alt="Снимок экрана 2024-04-13 в 11 43 22" src="https://github.com/basybemoog/cs50/assets/57913182/29d5f48d-b1b3-4eae-93aa-1806d8208fdc">

2024-04-13 09:01 UTC, fastrapier requested changes

2024-04-13 09:01 UTC, fastrapier commented on .gitignore
> +go.mod
Оставь этот файл в покое, он нужен, я не понимаю зачем ты хочешь его скрыть,он тебе мешает?

2024-04-14 20:10 UTC, fastrapier approved these changes

2024-04-14 20:10 UTC, merged