plurality solved
basybemoog/cs50 pull request #25
Opened 2024-04-12 10:19 UTC by basybemoog

2024-04-12 20:00 UTC, fastrapier requested changes
Нужны небольшие изменения

2024-04-12 20:00 UTC, fastrapier commented on problems/week_3/plurality/plurality.go
> +func Plurality(args int, argv []string) string {
Не понял зачем тебе нужен args, лишний аргумент как по мне, избавься от него и после я напишу тесты

2024-04-13 04:33 UTC, basybemoog commented on problems/week_3/plurality/plurality.go
> +func Plurality(args int, argv []string) string {
> Не понял зачем тебе нужен args, лишний аргумент как по мне, избавься от него и после я напишу тесты
Эту часть задачи писал не я, я только последние функции писал. это то, как было написано в дистрибутиве от CS50

2024-04-14 14:05 UTC, fastrapier approved these changes
ok

2024-04-14 14:05 UTC, merged